clear all;
fname = 'f_47.fig';
folder_path = 'D:/Dropbox/Thesis/MATLAB/';
fig = [folder_path,fname];
inf = openfig(fig);
C = gca;
title('');
xlabel('Distance (\mum)');
ylabel('x (\mum)');
yticks([-30,-15,0,15,30]);
set(C,'FontSize',20);
text(C,325,40,'f = 47\mum','FontSize',36,'FontWeight','bold','color','w');
savefig([folder_path,fname]);
saveas(gcf,[folder_path,'f_47.png']);